apiVersion: v1
kind: ConfigMap
metadata:
  name: forward-stub-config
data:
  config.json: |
    {
      "version": 5,
      "control": {
        "api": "",
        "timeout_sec": 5,
        "config_watch_interval": "2s",
        "pprof_port": -1
      },
      "logging": {
        "level": "info",
        "file": "/var/log/forward-stub/app.log",
        "traffic_stats_interval": "5s",
        "traffic_stats_sample_every": 1,
        "compress": true,
        "max_size_mb": 100,
        "max_backups": 5,
        "max_age_days": 30,
        "payload_log_max_bytes": 256
      },
      "receivers": {
        "udp_in": {
          "type": "udp_gnet",
          "listen": "0.0.0.0:19000",
          "multicore": true,
          "num_event_loop": 1,
          "socket_recv_buffer": 1048576
        }
      },
      "senders": {
        "udp_out": {
          "type": "udp_unicast",
          "local_ip": "0.0.0.0",
          "local_port": 19001,
          "remote": "127.0.0.1:19002",
          "concurrency": 1
        }
      },
      "pipelines": {
        "default": []
      },
      "selectors": {
        "udp-default": {
          "receivers": ["udp_in"],
          "tasks": ["udp-forward"]
        }
      },
      "tasks": {
        "udp-forward": {
          "pool_size": 1024,
          "queue_size": 4096,
          "execution_model": "fastpath",
          "pipelines": ["default"],
          "senders": ["udp_out"]
        }
      }
    }
