apiVersion: v1
kind: Service
metadata:
  name: forward-stub-udp
  labels:
    app.kubernetes.io/name: forward-stub
spec:
  selector:
    app.kubernetes.io/name: forward-stub
  ports:
    - name: udp-in
      protocol: UDP
      port: 19000
      targetPort: 19000
  type: ClusterIP
